NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
app_api:
    resource: "@AppApiBundle/Resources/config/routing.yml"
    prefix:   /api
    
app_web:
    resource: "@AppWebBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
rest:
    type: rest
    resource: "routing_rest.yml"
    prefix: /api
